version: "3"

env:
  DIR: "{{.TASKFILE_DIR}}"
  CONFIG_DIR: "{{.DIR}}/config"
  SECRETS_DIR: "{{.DIR}}/secrets"
  ARGOCD_SERVICE_DIR: "{{.DIR}}/argocd/service"
  ARGOCD_INGRESS_DIR: "{{.DIR}}/argocd/ingress"
  ARGOCD_APPLICATIONS_DIR: "{{.DIR}}/argocd/applications"

tasks:
  # =============================================================================
  # INDIVIDUAL COMPONENTS (Deploy specific services)
  # =============================================================================

  config:plan:
    desc: "📋 Plan Cluster Configuration changes"
    dir: "{{.CONFIG_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for Cluster Configuration.

  config:validate:
    desc: "✅ Validate Cluster Configuration configuration"
    dir: "{{.CONFIG_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the Cluster Configuration configuration.

  config:deploy:
    desc: "🚀 Deploy only Cluster Configuration"
    dir: "{{.CONFIG_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the Cluster Configuration component.

  config:destroy:
    desc: "💥 Destroy only Cluster Configuration"
    dir: "{{.CONFIG_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the Cluster Configuration component.

  config:output:
    desc: "📤 Show Cluster Configuration outputs"
    dir: "{{.CONFIG_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from Cluster Configuration.

  secrets:plan:
    desc: "📋 Plan External Secrets changes"
    dir: "{{.SECRETS_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for External Secrets

  secrets:validate:
    desc: "✅ Validate External Secrets configuration"
    dir: "{{.SECRETS_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the External Secrets configuration

  secrets:deploy:
    desc: "🚀 Deploy only External Secrets"
    dir: "{{.SECRETS_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the External Secrets component

  secrets:destroy:
    desc: "💥 Destroy only External Secrets"
    dir: "{{.SECRETS_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the External Secrets component

  secrets:output:
    desc: "📤 Show External Secrets outputs"
    dir: "{{.SECRETS_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from External Secrets

  # ArgoCD Service
  argocd:service:validate:
    desc: "✅ Validate ArgoCD Service configuration"
    dir: "{{.ARGOCD_SERVICE_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the ArgoCD Service configuration

  argocd:service:deploy:
    desc: "🚀 Deploy only ArgoCD Service"
    dir: "{{.ARGOCD_SERVICE_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the ArgoCD Service component

  argocd:service:destroy:
    desc: "💥 Destroy only ArgoCD Service"
    dir: "{{.ARGOCD_SERVICE_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the ArgoCD Service component

  argocd:service:output:
    desc: "📤 Show ArgoCD Service outputs"
    dir: "{{.ARGOCD_SERVICE_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from ArgoCD Service

  # ArgoCD Ingress
  argocd:ingress:plan:
    desc: "📋 Plan ArgoCD Ingress changes"
    dir: "{{.ARGOCD_INGRESS_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for ArgoCD Ingress

  argocd:ingress:validate:
    desc: "✅ Validate ArgoCD Ingress configuration"
    dir: "{{.ARGOCD_INGRESS_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the ArgoCD Ingress configuration

  argocd:ingress:deploy:
    desc: "🚀 Deploy only ArgoCD Ingress"
    dir: "{{.ARGOCD_INGRESS_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the ArgoCD Ingress component

  argocd:ingress:destroy:
    desc: "💥 Destroy only ArgoCD Ingress"
    dir: "{{.ARGOCD_INGRESS_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the ArgoCD Ingress component

  argocd:ingress:output:
    desc: "📤 Show ArgoCD Ingress outputs"
    dir: "{{.ARGOCD_INGRESS_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from ArgoCD Ingress

  # ArgoCD Applications
  argocd:applications:plan:
    desc: "📋 Plan ArgoCD Applications changes"
    dir: "{{.ARGOCD_APPLICATIONS_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for ArgoCD Applications

  argocd:applications:validate:
    desc: "✅ Validate ArgoCD Applications configuration"
    dir: "{{.ARGOCD_APPLICATIONS_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the ArgoCD Applications configuration

  argocd:applications:deploy:
    desc: "🚀 Deploy only ArgoCD Applications"
    dir: "{{.ARGOCD_APPLICATIONS_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the ArgoCD Applications component

  argocd:applications:destroy:
    desc: "💥 Destroy only ArgoCD Applications"
    dir: "{{.ARGOCD_APPLICATIONS_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the ArgoCD Applications component

  argocd:applications:output:
    desc: "📤 Show ArgoCD Applications outputs"
    dir: "{{.ARGOCD_APPLICATIONS_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from ArgoCD Applications
