version: "3"

env:
  DIR: "{{.TASKFILE_DIR}}"
  CONTROLLER_DIR: "{{.DIR}}/ingress/controller"
  RULES_DIR: "{{.DIR}}/ingress/rules"
  DNS_DIR: "{{.DIR}}/dns"

tasks:
  # =============================================================================
  # INDIVIDUAL COMPONENTS (Deploy specific services)
  # =============================================================================

  ingress:controller:plan:
    desc: "📋 Plan Ingress Controller changes"
    dir: "{{.CONTROLLER_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for Ingress Controller.

  ingress:controller:validate:
    desc: "✅ Validate Ingress Controller configuration"
    dir: "{{.CONTROLLER_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the Ingress Controller configuration.

  ingress:controller:deploy:
    desc: "🚀 Deploy only Ingress Controller"
    dir: "{{.CONTROLLER_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the Ingress Controller component.

  ingress:controller:destroy:
    desc: "💥 Destroy only Ingress Controller"
    dir: "{{.CONTROLLER_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the Ingress Controller component.

  ingress:controller:output:
    desc: "📤 Show Ingress Controller outputs"
    dir: "{{.CONTROLLER_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from Ingress Controller.

  ingress:rules:plan:
    desc: "📋 Plan Ingress Rules changes"
    dir: "{{.RULES_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for Ingress Rules.

  ingress:rules:validate:
    desc: "✅ Validate Ingress Rules configuration"
    dir: "{{.RULES_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the Ingress Rules configuration.

  ingress:rules:deploy:
    desc: "🚀 Deploy only Ingress Rules"
    dir: "{{.RULES_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the Ingress Rules component.

  ingress:rules:destroy:
    desc: "💥 Destroy only Ingress Rules"
    dir: "{{.RULES_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the Ingress Rules component.

  ingress:rules:output:
    desc: "📤 Show Ingress Rules outputs"
    dir: "{{.RULES_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from Ingress Rules.

  dns:plan:
    desc: "📋 Plan DNS changes"
    dir: "{{.DNS_DIR}}"
    cmds:
      - terragrunt plan --non-interactive
    summary: |
      Shows planned changes for DNS

  dns:validate:
    desc: "✅ Validate DNS configuration"
    dir: "{{.DNS_DIR}}"
    cmds:
      - terragrunt validate --non-interactive
    summary: |
      Validates the DNS configuration

  dns:deploy:
    desc: "🚀 Deploy only DNS"
    dir: "{{.DNS_DIR}}"
    cmds:
      - terragrunt apply --non-interactive -auto-approve
    summary: |
      Deploys only the DNS component

  dns:destroy:
    desc: "💥 Destroy only DNS"
    dir: "{{.DNS_DIR}}"
    cmds:
      - terragrunt destroy --non-interactive -auto-approve
    summary: |
      Destroys only the DNS component

  dns:output:
    desc: "📤 Show DNS outputs"
    dir: "{{.DNS_DIR}}"
    cmds:
      - terragrunt output --non-interactive
    summary: |
      Displays all outputs from DNS
